name: Android Release

on:
  push:
    branches:
      - dev
  pull_request:
    branches: 
      - dev

jobs:
  build:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Build with Gradle
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: ./gradlew assembleRelease --no-daemon

    - name: Sign APK
      id: sign_apk
      uses: r0adkll/sign-android-release@v1
      with:
        releaseDirectory: ./app/build/outputs/apk/release/
        signingKeyBase64: ${{ secrets.TEMP_SIGNING_KEYSTORE }}
        keyStorePassword: ${{ secrets.TEMP_SIGNING_KEYSTORE_PASSWORD }}
        alias: ${{ secrets.TEMP_SIGNING_KEY_ALIAS }}
        keyPassword: ${{ secrets.TEMP_SIGNING_KEY_PASSWORD }}

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: manager
        path: ${{steps.sign_apk.outputs.signedReleaseFile}}
